### PR TITLE
fix: added fileExistsSync method to core

### PR DESCRIPTION
**Pull request by WillieRuemmele**

### CODE REVIEW

**Comment by amphro** [comment]
How quickly do you need this?

**Comment by WillieRuemmele** [comment]
No Major rush, the WI will still be blocked by DRL

**Comment by tnoonan-salesforce** [comment]
@WillieRuemmele @amphro generally checking for a fileExisting is lack luster. It's better to check for read or write access instead.

**Comment by amphro** [comment]
Closing in favor of #284

**Pull request closed without merging**
