### PR TITLE
fix: adjust mock org test data to conform to v3

### PR DESCRIPTION
**Pull request by peternhale**
@W-10430285@

### CODE REVIEW

**Review by RodEsp — APPROVED** [review]
Looks good @peternhale but looks like some NUTs might need to be changed?

Do you know why this is returning a different error code now?

**Comment by peternhale** [comment]
> 

I did a search of repos looking for references to MockOrgTestData and the alias field. I could not find any. Do you know of specific nuts that are failing due to this change?

I did not change anything around error codes

**Comment by RodEsp** [comment]
@peternhale oh, I'm sorry... it's not NUTs...
[This build failure](https://app.circleci.com/pipelines/github/forcedotcom/sfdx-core/2126/workflows/48a5c795-2d91-45d7-851c-17cc17bd88fd/jobs/9256?invite=true#step-106-1122) is what I was talking about.

**Comment by RodEsp** [comment]
Weird, sounds good tho!

**Pull request merged**
